---
version: "2"
services:
  homer:
    build: .
    container_name: homer
    volumes:
    #to use a custom assets folder change /assets/ to the path to your custom folder
      - /assets/:/www/assets
    ports:
      - 80:8080
    user: 1000:1000 # default
    environment:
      - INIT_ASSETS=1 # default
